### ISSUE TITLE
colab badge malformed link

### ISSUE THREAD

**Issue by pwalczysko** [ome/ABIS-GBI-imaging-course-07-2023#1]
- click on Colab badge either in Readme or in the workshop.ipynb
- observe an error dialog from Colab ``malformed url.... ``

The url of the badge in this repo is
https://colab.research.google.com/github/ome/ABIS-GBI-imaging-course-07-2023/notebooks/

Whereas on the EMBL repo, the url of the colab badge was
https://colab.research.google.com/github/ome/EMBL-EBI-imaging-course-05-2023/

Cannot open a PR - forking on this repo is disabled.

cc @jburel

**Comment by pwalczysko** [comment]
Also the badge in setup.md has the same problem

**Comment by pwalczysko** [comment]
same for PublicResources.ipynb

I am afraid the colab badges need a full review

**Comment by jburel** [comment]
I will fix thanks

**Comment by jburel** [comment]
done
